app = 'finpilot'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[metrics]
  port = 9091
  path = "/metrics"

[env]
  NGINX_WORKER_TIMEOUT = "300s"