app = 'finpilot'
primary_region = 'cdg'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Changé à false pour éviter l'arrêt automatique
  auto_start_machines = true
  min_machines_running = 1    # Augmenté à 1 pour garder au moins une instance active

[[services]]
  protocol = "tcp"
  internal_port = 8080
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[metrics]
  port = 9091
  path = "/metrics"